ShowcaseScreen:
	name: 'Set PV data'

	Button:
		size_hint_y: None
		height: '36dp'
		text: 'Set Temperature'
		on_release: app.set_analog_val(set_tmp_input.text)

    CTextInput
        id: 'set_temp_input'
        size_hint_y: None
        height: '36dp'
        multiline: False
        text: 'PV value'

<CTextInput@TextInput>
    on_focus:
        screen = self.parent.parent.parent.parent
        if screen.parent: screen.focused = self